### ISSUE TITLE
Snap `get` and `set` methods should adhere to Python's built-in types

### ISSUE THREAD

**Issue by chanchiwai-ray** [canonical/operator-libs-linux#107]
Currently, `Snap.get` always returns the value as a string, and `Snap.set` always set the value as a string. It will be very helpful for these two methods to respect the types. For example, it will be nice that we can do the following

```python
s = snap.SnapCache()["some-snap"]
s.set({"foo": True,  "bar": {"a": 1, "b": 2.0, "c": None, "d": ["x", "y", "z"]}, "bar.greeting": "hello world", "buzz": 123, "fuzz": 123.123, "fizz": None})

x = s.get("foo")
y = s.get("bar")
y_1 = s.get("bar.a")
y_2 = s.get("bar.b")
# y_3 = s.get("bar.c") # None is not set
y_4 = s.get("bar.d")
y_5 = s.get("bar.greeting")
a = s.get("buzz")
b = s.get("fuzz")
# c = s.get("fizz") # None is not set

print(x, type(x))
print(y, type(y))
print(y_1, type(y_1))
print(y_2, type(y_2))
# print(y_3, type(y_3)) 
print(y_4, type(y_4))
print(y_5, type(y_5))
print(a, type(a))
print(b, type(b))
# print(c, type(c))
```

should prints

```shell
True <class 'bool'>
{'a': 1, 'b': 2.0, 'd': ['x', 'y', 'z'], 'greeting': 'hello world'} <class 'dict'>
1 <class 'int'>
2.0 <class 'float'>
['x', 'y', 'z'] <class 'list'>
hello world <class 'str'>
123 <class 'int'>
123.123 <class 'float'>
```

Example usages:

```python
# In app_1.py
s = snap.SnapCache()["some-snap"]
s.set({"logging.enable": True})

...

# In app_2.py
s = snap.SnapCache()["some-snap"]
# We can do 
if s.get("logging.enable"):
    do_something()
# Instead of
if s.get("logging.enable") == "True":
    do_something()
```

**Comment by benhoyt** [comment]
Thanks @chanchiwai-ray. I think this might be able to be achieved with `snap set -t` and `snap get -d`. However, would you like to make a concrete proposal for the changes here, either as a PR or a discussion here? Assuming we want to be backwards compatible, I think we'd either have to 1) keep using the `get`/`set` methods but add a `json=True` keyword arg, or 2) add new methods like `set_json` / `get_json`.

**Comment by chanchiwai-ray** [comment]
Hi @benhoyt, thanks for the comments. I've created a PR based on my idea, and with your suggestion (1) for compatibility.
