### ISSUE TITLE
[bug] Snap client `_wait` handles valid case as an error

### ISSUE THREAD

**Issue by Gu1nness** [canonical/operator-libs-linux#139]
## Description

The `SnapClient._wait` method ([here](https://github.com/canonical/operator-libs-linux/blob/f1952df48509dcdd51753eaa4a8ac7bb0357b27c/lib/charms/operator_libs_linux/v2/snap.py#L777)) considers a valid status `Do` as an error while it should not.

The [snapd REST API](https://snapcraft.io/docs/snapd-rest-api#heading--changes) specifies that the status can be `Do` for "Task is ready to start".
The filtering in the `SnapClient._wait` only considers the cases `Done` and `Doing`, `Valid` as valid cases and otherwise will raise a SnapError.
Similar to [this line](https://github.com/canonical/operator-libs-linux/blob/f1952df48509dcdd51753eaa4a8ac7bb0357b27c/lib/charms/operator_libs_linux/v2/snap.py#L790)), the status `Do` should sleep and wait for the task to start.

I can provide a patch if you want.

**Comment by benhoyt** [comment]
Makes sense to me. A patch would be great, thanks! Out of interest, how did you run across this? If it was due to an error, do you remember what command/operation you were running at the time?

**Comment by benhoyt** [comment]
Ah, I see you've opened #140 -- we'll take a look, thanks.

**Comment by Gu1nness** [comment]
> Makes sense to me. A patch would be great, thanks! Out of interest, how did you run across this? If it was due to an error, do you remember what command/operation you were running at the time?

I'm working on the MongoDB charms and I'm refactoring everything.
As part of this refactoring, I'm using the `Snap.set` method to configure my snaps and I noticed that it started happening quite often (which never happened in the past), with the error message showing a status `Do`
A quick investigation on the REST API and the operator-libs led me to this :)
