### ISSUE TITLE
service_resume doesn't raise Exceptions on failure returns false instead

### ISSUE THREAD

**Issue by MiaAltieri** [canonical/operator-libs-linux#33]
Hi! I'm using `service_resume` for my current development of a charm and I noticed that `service_resume` returns `True` when it succeeds and `False` otherwise. Would it be possible to implement some exceptions, it would be helpful to know when/why it fails to resume a service. I'm also happy to help implement this. @petevg

**Comment by petevg** [comment]
@MiaAltieri I went back and forth on whether or not to implement Exceptions.

I ended up going w/ the charmhelpers approach of returning true/false, which makes "is_running" work like everything else. I'm not sure that was the right choice, though.

The following code, for example, would address the problem, without adding too much complexity:

```
@@ -63,6 +63,10 @@ LIBAPI = 0
 LIBPATCH = 3
 
 
+class SystemdError(Exception):
+    pass
+
+
 def _popen_kwargs():
     return dict(
         stdout=subprocess.PIPE,
@@ -98,12 +102,25 @@ def _systemctl(
         logger.debug("Checking if '{}' is active".format(service_name))
 
     proc = subprocess.Popen(cmd, **_popen_kwargs())
+    last_line = ""
     for line in iter(proc.stdout.readline, ""):
+        last_line = line
         logger.debug(line)
 
     proc.wait()
-    return proc.returncode == 0
 
+    if sub_cmd == 'is-active':
+        if proc.returncode < 1:
+            return True
+        if proc.returncode == 3:  # TODO: is this the only possibilty?
+            return False
+
+    if proc.returncode > 0:
+        raise SystemdError('Could not {}{}. SystemD says: {}'.format(
+            sub_cmd,
+            " {}".format(service_name) if service_name else "",
+            last_line
+        ))
 
 def service_running(service_name: str) -> bool:
     """Determine whether a system service is running.
```

**Comment by MiaAltieri** [comment]
Hi @petevg . This looks great! Thanks for getting back to me so quickly. I think this should work fine, what is significance of a return code of 3?

**Comment by wolsen** [comment]
> Hi @petevg . This looks great! Thanks for getting back to me so quickly. I think this should work fine, what is significance of a return code of 3?

@MiaAltieri, the systemctl command uses LSB defined return codes and 3 means "program is not running" per the [manpage](https://manpages.ubuntu.com/manpages/focal/en/man1/systemctl.1.html) (see Exit Status).
