### ISSUE TITLE
passwd: not possible to set home directory for system user

### ISSUE THREAD

**Issue by mert-kirpici** [canonical/operator-libs-linux#52]
Currently it is not possible to create system users with a home directory using the public api of the `passwd` lib without specifying a password. However I think this is a valid use case. According to the `useradd` man page `-m, --create-home` flag must be passed for this to work.
```
...
-r, --system
           Create a system account.
...

           Note that useradd will not create a home directory for such a user, regardless of the default setting in /etc/login.defs (CREATE_HOME). You have to specify the -m options if you want a home directory for a
           system account to be created.
```

**Comment by benhoyt** [comment]
This was fixed with https://github.com/canonical/operator-libs-linux/pull/53 -- thanks.

Though we may need to bump up the patch version?
