### ISSUE TITLE
Should `snap.hold_refresh` change it's functionality to allow for infinite holds?

### ISSUE THREAD

**Issue by zmraul** [canonical/operator-libs-linux#80]
Currently setting `snap.hold_refresh(days=0)` will remove the hold on the snaps. What value would be reasonable to allow for indefinite holds?

**Comment by benhoyt** [comment]
I don't think there is a way currently, as the `hold_refresh` function checks that days is less than or equal to 90 and raises a `ValueError` if not. However, as of Aug 2022 ([this snapd commit](https://github.com/snapcore/snapd/commit/e226d30a3c85ae90f1fe43f8d81ceb00f0dc7f4b)), snap allows the `refresh.hold` config option to be set to "forever" (a user can do this with `snap refresh --hold` or `sudo snap set system refresh.hold=forever`) to allow indefinite holds.

I'd be in favour of a PR that allows `hold_refresh(forever=True)` option that enabled this. @zmraul Would you be willing to put up a PR with tests?

I though about `hold_refresh(days=None)` but I think it's a bit confusing that it would allow `days=0` to mean no hold and `days=None` to mean indefinite (especially when both 0 and None are falsey in Python).

**Comment by jnsgruk** [comment]
Agree with the proposal for `hold_refresh(forever=True)` - there are some other bits that landed recently like snap install by revision too

**Comment by jnsgruk** [comment]
(I should also mention that a really important feature is the **per snap** hold you can now do - we should think about implementing that)
